public enum TileIndex
{
    VERTICAL,
    HORIZONTAL,
    CROSSROADS,
    TURN_NW,
    TURN_SW,
    TURN_SE,
    TURN_NE,
    T_JUNCTION_UP_CLOSED,
    T_JUNCTION_RIGHT_CLOSED,
    T_JUNCTION_DOWN_CLOSED,
    T_JUNCTION_LEFT_CLOSED,
    HORIZONTAL_LEFT,
    HORIZONTAL_RIGHT,
    VERTICAL_DOWN,
    VERTICAL_UP
}